minecraft_version=26.3
minecraft_dependency=>=26.3

# Build Information
# The target mc versions for the mod during mod publishing, separated with \n
game_versions=26.3

# https://www.fabricmc.net/develop/
fabric_api_version=0.161.0+26.3

# https://modrinth.com/mod/modmenu/versions?g=26.3&l=fabric
modmenu=21.0.0

# https://modrinth.com/mod/cloth-config/versions?g=26.3&l=fabric
cloth-config=26.3.159+fabric